# Generated by Django 2.0.2 on 2018-03-25 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=128, verbose_name='Название категории')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_translated', models.BooleanField(default=False, verbose_name='Перевод')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_number', models.CharField(default='', max_length=9, verbose_name='Артикул')),
                ('title', models.CharField(default='', max_length=32, verbose_name='Название')),
                ('description', models.CharField(default='', max_length=64, verbose_name='Короткое описание')),
                ('price', models.FloatField(default=0, verbose_name='Цена')),
                ('url_ikea', models.CharField(blank=True, default='', max_length=256, verbose_name='Ссылка')),
                ('url', models.CharField(blank=True, default='', max_length=256, verbose_name='Ссылка')),
                ('available', models.IntegerField(default=0, verbose_name='Наличие')),
                ('key_feautures', models.CharField(blank=True, default='', max_length=512, verbose_name='Основное описание')),
                ('good_to_know', models.CharField(blank=True, default='', max_length=512, verbose_name='Полезно знать')),
                ('care_instructions', models.CharField(blank=True, default='', max_length=512, verbose_name='Инструкция по уходу')),
                ('materials_info', models.CharField(blank=True, default='', max_length=512, verbose_name='Материал')),
                ('dimensions', models.CharField(blank=True, default='', max_length=128, verbose_name='Габариты')),
                ('designed_by', models.CharField(blank=True, default='', max_length=32, verbose_name='Создатель')),
                ('complementary_products', models.CharField(blank=True, default='', max_length=512, verbose_name='Дополняющие продукты')),
                ('color_options', models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='Другие цвета')),
                ('color', models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='Цвет')),
                ('is_translated', models.BooleanField(default=False, verbose_name='Перевод')),
                ('is_parsed', models.BooleanField(default=False, verbose_name='Скачанно')),
                ('unique_identificator', models.CharField(default='', max_length=8, verbose_name='Идентификатор')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='products/', verbose_name='Изображение')),
                ('title', models.CharField(default='', max_length=16, verbose_name='Название')),
                ('size', models.SmallIntegerField(default=0, verbose_name='Размер, px')),
                ('product', models.ManyToManyField(to='ikea_parser.Product', verbose_name='Продукт, id')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=128, verbose_name='Название подкатегории')),
                ('url', models.CharField(blank=True, default='', max_length=256, verbose_name='Ссылка')),
                ('url_ikea', models.CharField(blank=True, default='', max_length=256, verbose_name='Ссылка')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_translated', models.BooleanField(default=False, verbose_name='Перевод')),
                ('have_sub_subcategory', models.BooleanField(default=False, verbose_name='Под под категория')),
                ('unique_identificator', models.CharField(max_length=8, verbose_name='Идентификатор')),
                ('priority', models.BooleanField(default=False, verbose_name='Приоритет')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ikea_parser.Category', verbose_name='Категория, id')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='SubSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=128, verbose_name='Название подкатегории')),
                ('url', models.CharField(blank=True, default='', max_length=256, verbose_name='Ссылка')),
                ('url_ikea', models.CharField(blank=True, default='', max_length=256, verbose_name='Ссылка')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_translated', models.BooleanField(default=False, verbose_name='Перевод')),
                ('unique_identificator', models.CharField(max_length=8, verbose_name='Идентификатор')),
                ('priority', models.BooleanField(default=False, verbose_name='Приоритет')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ikea_parser.SubCategory', verbose_name='Подкатегория, id')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='sub_subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ikea_parser.SubSubCategory', verbose_name='Под подкатегория, id'),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ikea_parser.SubCategory', verbose_name='Подкатегория, id'),
        ),
    ]
