# Generated by Django 2.0.2 on 2018-03-31 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ikea_parser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additional_models',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Модели'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='ikea_parser.Category', verbose_name='Категория, id'),
        ),
    ]
