# Generated by Django 2.0.2 on 2018-03-31 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikea_parser', '0002_auto_20180331_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='parse_later',
            field=models.BooleanField(default=False, verbose_name='Парсить позже'),
        ),
    ]
