# Generated by Django 2.0.3 on 2018-03-31 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ikea_parser', '0002_auto_20180330_0942'),
        ('ikea_parser', '0003_product_parse_later'),
    ]

    operations = [
    ]
