# Generated by Django 2.0.3 on 2018-04-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikea_parser', '0004_merge_20180331_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sub_subcategory',
        ),
        migrations.AddField(
            model_name='product',
            name='sub_subcategory',
            field=models.ManyToManyField(to='ikea_parser.SubSubCategory', verbose_name='Под подкатегория, id'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ManyToManyField(to='ikea_parser.SubCategory', verbose_name='Подкатегория, id'),
        ),
    ]
